spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      driver-class-name: org.h2.Driver
      pool-name: CoreConnectionPool
      url: jdbc:h2:mem:urban_test
      username: sa
      password:
      maximum-pool-size: 100
      idle-timeout: 30000
    initialization-mode: always